//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./stats_types');
//HELPER FUNCTIONS AND STRUCTURES

var statsCalculationService_mean_args = function(args) {
  this.argList = null;
  if (args) {
    if (args.argList !== undefined && args.argList !== null) {
      this.argList = Thrift.copyList(args.argList, [null]);
    }
  }
};
statsCalculationService_mean_args.prototype = {};
statsCalculationService_mean_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.argList = [];
        var _rtmp31 = input.readListBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var elem3 = null;
          elem3 = input.readI32();
          this.argList.push(elem3);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_mean_args.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_mean_args');
  if (this.argList !== null && this.argList !== undefined) {
    output.writeFieldBegin('argList', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.argList.length);
    for (var iter4 in this.argList) {
      if (this.argList.hasOwnProperty(iter4)) {
        iter4 = this.argList[iter4];
        output.writeI32(iter4);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_mean_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
statsCalculationService_mean_result.prototype = {};
statsCalculationService_mean_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.DOUBLE) {
        this.success = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_mean_result.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_mean_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.DOUBLE, 0);
    output.writeDouble(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_median_args = function(args) {
  this.argList = null;
  if (args) {
    if (args.argList !== undefined && args.argList !== null) {
      this.argList = Thrift.copyList(args.argList, [null]);
    }
  }
};
statsCalculationService_median_args.prototype = {};
statsCalculationService_median_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.argList = [];
        var _rtmp36 = input.readListBegin();
        var _size5 = _rtmp36.size || 0;
        for (var _i7 = 0; _i7 < _size5; ++_i7) {
          var elem8 = null;
          elem8 = input.readI32();
          this.argList.push(elem8);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_median_args.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_median_args');
  if (this.argList !== null && this.argList !== undefined) {
    output.writeFieldBegin('argList', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.argList.length);
    for (var iter9 in this.argList) {
      if (this.argList.hasOwnProperty(iter9)) {
        iter9 = this.argList[iter9];
        output.writeI32(iter9);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_median_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
statsCalculationService_median_result.prototype = {};
statsCalculationService_median_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.DOUBLE) {
        this.success = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_median_result.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_median_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.DOUBLE, 0);
    output.writeDouble(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_variance_args = function(args) {
  this.argList = null;
  if (args) {
    if (args.argList !== undefined && args.argList !== null) {
      this.argList = Thrift.copyList(args.argList, [null]);
    }
  }
};
statsCalculationService_variance_args.prototype = {};
statsCalculationService_variance_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.argList = [];
        var _rtmp311 = input.readListBegin();
        var _size10 = _rtmp311.size || 0;
        for (var _i12 = 0; _i12 < _size10; ++_i12) {
          var elem13 = null;
          elem13 = input.readI32();
          this.argList.push(elem13);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_variance_args.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_variance_args');
  if (this.argList !== null && this.argList !== undefined) {
    output.writeFieldBegin('argList', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.I32, this.argList.length);
    for (var iter14 in this.argList) {
      if (this.argList.hasOwnProperty(iter14)) {
        iter14 = this.argList[iter14];
        output.writeI32(iter14);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_variance_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
statsCalculationService_variance_result.prototype = {};
statsCalculationService_variance_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.DOUBLE) {
        this.success = input.readDouble();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_variance_result.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_variance_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.DOUBLE, 0);
    output.writeDouble(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_genRandom_args = function(args) {
};
statsCalculationService_genRandom_args.prototype = {};
statsCalculationService_genRandom_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_genRandom_args.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_genRandom_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationService_genRandom_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
  }
};
statsCalculationService_genRandom_result.prototype = {};
statsCalculationService_genRandom_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp316 = input.readListBegin();
        var _size15 = _rtmp316.size || 0;
        for (var _i17 = 0; _i17 < _size15; ++_i17) {
          var elem18 = null;
          elem18 = input.readI32();
          this.success.push(elem18);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

statsCalculationService_genRandom_result.prototype.write = function(output) {
  output.writeStructBegin('statsCalculationService_genRandom_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.I32, this.success.length);
    for (var iter19 in this.success) {
      if (this.success.hasOwnProperty(iter19)) {
        iter19 = this.success[iter19];
        output.writeI32(iter19);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var statsCalculationServiceClient = exports.Client = function(output, pClass) {
  this.output = output;
  this.pClass = pClass;
  this._seqid = 0;
  this._reqs = {};
};
statsCalculationServiceClient.prototype = {};
statsCalculationServiceClient.prototype.seqid = function() { return this._seqid; };
statsCalculationServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };

statsCalculationServiceClient.prototype.mean = function(argList, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_mean(argList);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_mean(argList);
  }
};

statsCalculationServiceClient.prototype.send_mean = function(argList) {
  var output = new this.pClass(this.output);
  var params = {
    argList: argList
  };
  var args = new statsCalculationService_mean_args(params);
  try {
    output.writeMessageBegin('mean', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

statsCalculationServiceClient.prototype.recv_mean = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new statsCalculationService_mean_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('mean failed: unknown result');
};

statsCalculationServiceClient.prototype.median = function(argList, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_median(argList);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_median(argList);
  }
};

statsCalculationServiceClient.prototype.send_median = function(argList) {
  var output = new this.pClass(this.output);
  var params = {
    argList: argList
  };
  var args = new statsCalculationService_median_args(params);
  try {
    output.writeMessageBegin('median', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

statsCalculationServiceClient.prototype.recv_median = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new statsCalculationService_median_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('median failed: unknown result');
};

statsCalculationServiceClient.prototype.variance = function(argList, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_variance(argList);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_variance(argList);
  }
};

statsCalculationServiceClient.prototype.send_variance = function(argList) {
  var output = new this.pClass(this.output);
  var params = {
    argList: argList
  };
  var args = new statsCalculationService_variance_args(params);
  try {
    output.writeMessageBegin('variance', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

statsCalculationServiceClient.prototype.recv_variance = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new statsCalculationService_variance_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('variance failed: unknown result');
};

statsCalculationServiceClient.prototype.genRandom = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_genRandom();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_genRandom();
  }
};

statsCalculationServiceClient.prototype.send_genRandom = function() {
  var output = new this.pClass(this.output);
  var args = new statsCalculationService_genRandom_args();
  try {
    output.writeMessageBegin('genRandom', Thrift.MessageType.CALL, this.seqid());
    args.write(output);
    output.writeMessageEnd();
    return this.output.flush();
  }
  catch (e) {
    delete this._reqs[this.seqid()];
    if (typeof output.reset === 'function') {
      output.reset();
    }
    throw e;
  }
};

statsCalculationServiceClient.prototype.recv_genRandom = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new statsCalculationService_genRandom_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('genRandom failed: unknown result');
};
var statsCalculationServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
};
statsCalculationServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
};
statsCalculationServiceProcessor.prototype.process_mean = function(seqid, input, output) {
  var args = new statsCalculationService_mean_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.mean.length === 1) {
    Q.fcall(this._handler.mean.bind(this._handler),
      args.argList
    ).then(function(result) {
      var result_obj = new statsCalculationService_mean_result({success: result});
      output.writeMessageBegin("mean", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("mean", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.mean(args.argList, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new statsCalculationService_mean_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("mean", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("mean", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
statsCalculationServiceProcessor.prototype.process_median = function(seqid, input, output) {
  var args = new statsCalculationService_median_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.median.length === 1) {
    Q.fcall(this._handler.median.bind(this._handler),
      args.argList
    ).then(function(result) {
      var result_obj = new statsCalculationService_median_result({success: result});
      output.writeMessageBegin("median", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("median", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.median(args.argList, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new statsCalculationService_median_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("median", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("median", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
statsCalculationServiceProcessor.prototype.process_variance = function(seqid, input, output) {
  var args = new statsCalculationService_variance_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.variance.length === 1) {
    Q.fcall(this._handler.variance.bind(this._handler),
      args.argList
    ).then(function(result) {
      var result_obj = new statsCalculationService_variance_result({success: result});
      output.writeMessageBegin("variance", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("variance", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.variance(args.argList, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new statsCalculationService_variance_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("variance", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("variance", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
statsCalculationServiceProcessor.prototype.process_genRandom = function(seqid, input, output) {
  var args = new statsCalculationService_genRandom_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.genRandom.length === 0) {
    Q.fcall(this._handler.genRandom.bind(this._handler)
    ).then(function(result) {
      var result_obj = new statsCalculationService_genRandom_result({success: result});
      output.writeMessageBegin("genRandom", Thrift.MessageType.REPLY, seqid);
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    }).catch(function (err) {
      var result;
      result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
      output.writeMessageBegin("genRandom", Thrift.MessageType.EXCEPTION, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  } else {
    this._handler.genRandom(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new statsCalculationService_genRandom_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("genRandom", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("genRandom", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
